# Question

The dataset used contains the list of patients having breast cancer with 8 input independent variables describing the different
characteristics of the canacer and the output being a classifictaion of the cancer into benign or malignate.

# Solutions

In [2]:
#K - Nearest Neighbor Classifier

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing datasets

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : , -1].values

#Splitting the dataset into training and test sets

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

#Predicting new Result

Predict_X_test = classifier.predict(X_test)
#print(Predict_X_test)

#) Making the confusion matrix for score 

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(Y_test, Predict_X_test)
print(cm)

'''
[ TRUE NEGATIVES] [FALSE POSITIVE]\n
[FALSE NEGATIVES] [ TRUE POSITIVE]

'''
accuracy_score(Y_test, Predict_X_test)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

[[83  4]
 [ 2 48]]

0.9562043795620438

In [3]:
#Decision Tree

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
#display(dataset)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

#Splitting the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)                                                       

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

#Predicting Test Results
Predict_Y = classifier.predict(X_test)

#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Predict_Y)
print('Confusion Matrix')
print(cm, end = '\n\n')
print('Accuracy Score')
accuracy_score(Y_test, Predict_Y)

Confusion Matrix
[[103   4]
 [  3  61]]

Accuracy Score

0.9590643274853801

In [4]:
#Kernel SVM

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

#Splitting the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)                                                       

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, Y_train)

#Predicting Test Results
Predict_Y = classifier.predict(X_test)

#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Predict_Y)
print('Confusion Matrix')
print(cm, end = '\n\n')
print('Accuracy Score')
accuracy_score(Y_test, Predict_Y)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

Confusion Matrix
[[102   5]
 [  3  61]]

Accuracy Score

0.9532163742690059

In [5]:
#Logistic Regression

#Importing Libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing Dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : , -1].values

#Splitting the Dataset into Train and Test Set.

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

#Feature Scaling

#It is not required for Logistic Regression but applying it makes the model more accuarte, hence we apply it.
#To avoid information leakage from the test set feature scaling is absolutely necessary

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training on the Training Set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)

#Predicting new Result

Predict_X_test = classifier.predict(X_test)
#print(Predict_X_test)

#Making the Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(Y_test, Predict_X_test)
print(cm)

accuracy_score(Y_test, Predict_X_test)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

[[103   4]
 [  5  59]]

0.9473684210526315

In [6]:
#Naive Bayes Classifier 
#The only change with respecet to the SVM Classifier is at the Training part where kernel = 'rbf' instead of 'linear'.

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

#Reshaping the dataset
#Y = Y.reshape(len(Y),1)

#Splitting the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)                                                       

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

#Predicting Test Results
Predict_Y = classifier.predict(X_test)

#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Predict_Y)
print('Confusion Matrix')
print(cm, end = '\n\n')
print('Accuracy Score')
accuracy_score(Y_test, Predict_Y)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

Confusion Matrix
[[99  8]
 [ 2 62]]

Accuracy Score

0.9415204678362573

In [7]:
#Random Forest Classifier 

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

#Reshaping the dataset
#Y = Y.reshape(len(Y),1)

#Splitting the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)                                                       

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

#Predicting Test Results
Predict_Y = classifier.predict(X_test)

#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Predict_Y)
print('Confusion Matrix')
print(cm, end = '\n\n')
print('Accuracy Score')
accuracy_score(Y_test, Predict_Y)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

Confusion Matrix
[[103   4]
 [  5  59]]

Accuracy Score

0.9473684210526315

In [8]:
#Support Vector Machine

#Solution

#Importing Libraries

import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

#Importing dataset

my_file = open('C:\\Users\\Maverick\\Machine Learning\\Breast_Cancer_Data.csv')
dataset = pd.read_csv(my_file)
display(dataset)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

#Reshaping the dataset
#Y = Y.reshape(len(Y),1)

#Splitting the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)                                                       

#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the model

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)


#Predicting Test Results

Predict_Y = classifier.predict(X_test)

#Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Predict_Y)
print('Confusion Matrix')
print(cm, end = '\n\n')
print('Accuracy Score')
accuracy_score(Y_test, Predict_Y)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
678,776715,3,1,1,1,3,2,1,1,1,2
679,841769,2,1,1,1,2,1,1,1,1,2
680,888820,5,10,10,3,7,3,8,10,2,4
681,897471,4,8,6,4,3,4,10,6,1,4
682,897471,4,8,8,5,4,5,10,4,1,4

Confusion Matrix
[[102   5]
 [  5  59]]

Accuracy Score

0.9415204678362573

# What to choose where

In [9]:
'''
What are the pros and cons of each model ?
How do I know which model to choose for my problem ?
How can I improve each of these models ?
'''

#Let's answer each of these questions one by one:

'''1. What are the pros and cons of each model ?'''

#Please find attached at the bottom of this article a cheat-sheet that gives you all the pros and the cons of each 
#classification model.

'''2. How do I know which model to choose for my problem ?'''

#Same as for regression models, you first need to figure out whether your problem is linear or non linear.

#If your problem is linear, you should go for Logistic Regression or SVM.
#If your problem is non linear, you should go for K-NN, Naive Bayes, Decision Tree or Random Forest.

#Then from a business point of view, you would rather use:

#Logistic Regression or Naive Bayes when you want to rank your predictions by their probability. 
#For example if you want to rank your customers from the highest probability that they buy a certain product, to the lowest
#probability. Eventually that allows you to target your marketing campaigns. And of course for this type of business problem, 
#you should use Logistic Regression if your problem is linear, and Naive Bayes if your problem is non linear.

#SVM when you want to predict to which segment your customers belong to. Segments can be any kind of segments, for example some 
#market segments you identified earlier with clustering.

#Decision Tree when you want to have clear interpretation of your model results,

#Random Forest when you are just looking for high performance with less need for interpretation. 

'''3. How can I improve each of these models ?'''

#Parameter Tuning allows you to improve the performance of your models, by tuning them. You probably already noticed that each 
#model is composed of two types of parameters:

#1). The parameters that are learnt, for example the coefficients in Linear Regression,
#2). The hyperparameters.

#The hyperparameters are the parameters that are not learnt and that are fixed values inside the model equations. 
#For example, the regularization parameter lambda or the penalty parameter C are hyperparameters. 
#So far we used the default value of these hyperparameters, and we haven't searched for their optimal value so that your model 
#reaches even higher performance. Finding their optimal value is exactly what Parameter Tuning is about.

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00x\x00x\x00\x00\xff\xe1\x10\xf8Exif\x00\x00MM\x00â€¦